[wpeframework-plugins] bump version and cleanup

diff --git a/package/wpe/wpeframework-plugins/S35WPEFrameworkBluetooth b/package/wpe/wpeframework-plugins/S35WPEFrameworkBluetooth
--- a/package/wpe/wpeframework-plugins/S35WPEFrameworkBluetooth
+++ b/package/wpe/wpeframework-plugins/S35WPEFrameworkBluetooth
@@ -2,41 +2,17 @@
 
 start() {
 	if [ -f /usr/bin/hciattach ]; then
-		echo -n "Flashing Blutooth firmware"
-		/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow
 		if [ ! -d "/sys/class/bluetooth/hci0" ]; then
 			sleep 3
-			/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow
-			[ $? == 0 ] && echo "OK" || echo "FAIL"
-		else
-			echo "OK"
 		fi
-	fi
-	if [ -f /usr/libexec/bluetooth/bluetoothd ]; then
-		echo -n "Starting bluetoothd daemon"
-		/usr/libexec/bluetooth/bluetoothd &
-		[ $? == 0 ] && echo "OK" || echo "FAIL"
-	fi
-	if [ -f /usr/bin/bluealsa ]; then
-		echo -n "Starting bluealsa daemon"
-		/usr/bin/bluealsa &
-		[ $? == 0 ] && echo "OK" || echo "FAIL"
+		/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow
+		[ $? == 0 ] && /usr/bin/hciconfig hci0 up && echo "OK" || echo "FAIL"
 	fi
 }
 stop() {
-	if [ -f /usr/libexec/bluetooth/bluetoothd ]; then
-		echo -n "Stopping bluetoothd daemon"
-		killall -9 bluetoothd
-		[ $? == 0 ] && echo "OK" || echo "FAIL"
-	fi
-	if [ -f /usr/bin/bluealsa ]; then
-		echo -n "Stopping bluealsa daemon"
-		killall -9 bluealsa
-		[ $? == 0 ] && echo "OK" || echo "FAIL"
-	fi
 	if [ -f /usr/bin/hciattach ]; then
-		echo -n "Stopping hci0 bluetooth interface"
 		/usr/bin/hciconfig hci0 down
+		killall -9 hciattach
 	fi
 }
 restart() {
