[bluetooth-plugin] Running bluealsa daemon in bluetooth startup script

diff --git a/package/wpe/wpeframework-plugins/S70WPEFrameworkBluetooth b/package/wpe/wpeframework-plugins/S70WPEFrameworkBluetooth
--- a/package/wpe/wpeframework-plugins/S70WPEFrameworkBluetooth
+++ b/package/wpe/wpeframework-plugins/S70WPEFrameworkBluetooth
@@ -4,8 +4,9 @@ start() {
     echo -n "Running bluetooth startup script"
     if [ -f /usr/bin/hciattach ]; then
         echo -n "Flashing Blutooth firmware"
-        if [ $? != 0 ]
-        then
+        /usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow
+        if [ ! -d "/sys/class/bluetooth/hci0" ]; then
+            sleep 3
             /usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow
             [ $? == 0 ] && echo "OK" || echo "FAIL"
         else
@@ -18,10 +19,20 @@ start() {
         /usr/libexec/bluetooth/bluetoothd &
         [ $? == 0 ] && echo "OK" || echo "FAIL"
     fi
+
+    if [ -f /usr/bin/bluealsa ]; then
+        echo -n "Starting bluealsa daemon"
+        /usr/bin/bluealsa &
+        [ $? == 0 ] && echo "OK" || echo "FAIL"
+    fi
 }
 stop() {
 	echo -n "Stopping bluetoothd daemon"
 	killall -9 bluetoothd
+	[ $? == 0 ] && echo "OK" || echo "FAIL"
+
+	echo -n "Stopping bluealsa daemon"
+	killall -9 bluealsa
 	[ $? == 0 ] && echo "OK" || echo "FAIL"
 }
 restart() {
