[webbridge] cleaning up init.d script

diff --git a/package/webbridge/S80webbridge b/package/webbridge/S80webbridge
--- a/package/webbridge/S80webbridge
+++ b/package/webbridge/S80webbridge
@@ -2,33 +2,34 @@
 
 start() {
 	echo -n "Starting webbridge: "
+	sleep 1
 	start-stop-daemon -S -q -b -m -p /var/run/webbridge.pid --exec /usr/bin/webbridge -- -b </dev/null >/dev/null 2>&1
 	[ $? == 0 ] && echo "OK" || echo "FAIL"
 }
 stop() {
-    echo -n "Stopping webbridge: "
-    start-stop-daemon -K -q -p /var/run/webbridge.pid
-    [ $? == 0 ] && echo "OK" || echo "FAIL"
-    rm -rf /var/run/webbridge.pid
+	echo -n "Stopping webbridge: "
+	start-stop-daemon -K -q -p /var/run/webbridge.pid
+	[ $? == 0 ] && echo "OK" || echo "FAIL"
+	rm -rf /var/run/webbridge.pid
 }
 restart() {
-    stop
-    start
+	stop
+	start
 }
 
 case "$1" in
-  start)
-    start
-    ;;
-  stop)
-    stop
-    ;;
-  restart|reload)
-    restart
-    ;;
-  *)
-    echo "Usage: $0 {start|stop|restart}"
-    exit 1
+	start)
+		start
+		;;
+	stop)
+		stop
+		;;
+	restart|reload)
+		restart
+		;;
+	*)
+		echo "Usage: $0 {start|stop|restart}"
+		exit 1
 esac
 
 exit $?
